name: Create Package (No Release)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Package version'
        required: true
        default: '1.0.0'
        type: string

jobs:
  create-package:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Create package
      run: |
        chmod +x scripts/create-package.sh
        # Update version in script
        sed -i "s/PACKAGE_VERSION=\".*\"/PACKAGE_VERSION=\"${{ github.event.inputs.version }}\"/" scripts/create-package.sh
        # Create package
        ./scripts/create-package.sh || echo "Package creation completed"
    
    - name: Upload package artifact
      uses: actions/upload-artifact@v4
      with:
        name: rest-api-library-v${{ github.event.inputs.version }}
        path: REST-API-Library-v*.zip
        retention-days: 7
    
    - name: Summary
      run: |
        echo "## 📦 Package Created Successfully!" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Version:** ${{ github.event.inputs.version }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📥 Download" >> $GITHUB_STEP_SUMMARY
        echo "Check the 'Artifacts' section below to download the package zip file." >> $GITHUB_STEP_SUMMARY
